name: hmu_library_website
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_styled_toast: ^2.0.0
  google_fonts: ^2.1.0
  http: ^0.13.4
  recase: ^4.0.0
  riverpod: ^1.0.2
  url_launcher: ^6.0.17
  validators: ^3.0.0
  address_search_field: ^4.0.1
  accordion: ^2.1.2
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/hmu_lib_5.jpg
    - assets/images/hmu_logo.png
